EquipmentRent/Pages/ShoppingCart/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using EquipmentRent.Models;

namespace EquipmentRent.Pages.ShoppingCart
{
    public class DeleteModel : PageModel
    {
        private readonly EquipmentRent.Models.EquipmentRentContext _context;

        public DeleteModel(EquipmentRent.Models.EquipmentRentContext context)
        {
            _context = context;
        }

        [BindProperty]
        public CartItem CartItem { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            CartItem = await _context.CartItem.FirstOrDefaultAsync(m => m.ID == id);

            if (CartItem == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            CartItem = await _context.CartItem.FindAsync(id);

            if (CartItem != null)
            {
                _context.CartItem.Remove(CartItem);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

EquipmentRent/Pages/ShoppingCart/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using EquipmentRent.Models;
using EquipmentRent.Data;

namespace EquipmentRent.Pages.ShoppingCart
{
    public class IndexModel : PageModel
    {
        private readonly EquipmentRent.Models.EquipmentRentContext _context;

        public IndexModel(EquipmentRent.Models.EquipmentRentContext context)
        {
            _context = context;
        }

        public IList<CartItem> CartItem { get;set; }

        public async Task OnGetAsync()
        {
            CartItem = await _context.CartItem
                .Include(i => i.Item)
                .ToListAsync();
        }

        public ActionResult OnPostGetInvoice()
        {
            MemoryStream memoryStream = new MemoryStream();
            TextWriter textWriter = new StreamWriter(memoryStream);
            decimal totalCost = 0;
            int totalLoyalityPoints = 0;
            string separator = " | ";

            textWriter.WriteLine("INVOICE");
            textWriter.WriteLine("");

            foreach (var item in _context.CartItem.Include(i => i.Item).ToArray())
            {
                decimal itemCost = CalculateCost(item.Item.Type, item.RentLength);
                totalCost = totalCost + itemCost;

                int loyalityPoints = LoyalityPoints(item.Item.Type);
                totalLoyalityPoints = totalLoyalityPoints + loyalityPoints;

                string name = item.Item.Name;
                string length = item.RentLength.ToString() + " days";
                string cost = itemCost.ToString("F") + " euros";
                
                string itemString = name + separator + length + separator + cost;

                textWriter.WriteLine(itemString);
            }
            textWriter.WriteLine("");
            textWriter.WriteLine("TOTAL: " + totalCost.ToString("F") + " euros");
            textWriter.WriteLine("LOYALITY POINTS GAINED: " + "+" + totalLoyalityPoints.ToString());

            textWriter.Flush();
            memoryStream.Position = 0;

            return File(memoryStream, "application/force-download", "myFile.txt");
        }

        private decimal CalculateCost(string type, int rentLength)
        {
            decimal oneTimeFee = 100;
            decimal premiumDailyFee = 60;
            decimal regularDailyFee = 40;
            decimal cost = 0;

            //One time fee
            if (type != "Specialized")
            {
                cost = cost + oneTimeFee;
            }

            if (type == "Heavy")
            {
                decimal premiumFee = premiumDailyFee * rentLength;
                cost = cost + premiumFee;
            }
            else if (type == "Regular")
            {
                if (rentLength > 2)
                {
                    decimal premiumFee = premiumDailyFee * 2;
                    int adjustedLength = rentLength - 2;
                    decimal regularFee = adjustedLength * regularDailyFee;

                    cost = cost + premiumFee + regularFee;
                }
                else
                {
                    decimal premiumFee = rentLength * premiumDailyFee;

                    cost = cost + premiumFee;
                }
            }
            else if (type == "Specialized")
            {
                if (rentLength > 3)
                {
                    decimal premiumFee = premiumDailyFee * 3;
                    int adjustedLength = rentLength - 3;
                    decimal regularFee = adjustedLength * regularDailyFee;

                    cost = cost + premiumFee + regularFee;
                }
                else
                {
                    decimal premiumFee = premiumDailyFee * rentLength;

                    cost = cost + premiumFee;
                }
            }

            return cost;
        }

        private int LoyalityPoints(string type)
        {
            if (type == "heavy")
            {
                return 2;
            }
            else
            {
                return 1;
            }
        }
    }
}

EquipmentRent/Pages/ShoppingCart/Delete.cshtml
@page
@model EquipmentRent.Pages.ShoppingCart.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CartItem</h4>
    <hr />
    <dl class="row">
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="CartItem.ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

EquipmentRent/Pages/ShoppingCart/Index.cshtml
@page
@model EquipmentRent.Pages.ShoppingCart.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CartItem[0].Item)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CartItem[0].Item.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CartItem[0].RentLength)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.CartItem) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RentLength)
            </td>
            <td>
                <a asp-page="./Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
<div>
    <form asp-page-handler="GetInvoice" method="post">
        <input type="submit" value="Get Invoice" class="btn btn-success" />
    </form>
</div>